apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-app-py-dpl
  labels:
    app: hello-app-py
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-app-py
  template:
    metadata:
      name: hello-app-py
      labels:
        app: hello-app-py

    spec:
      containers:
      - name: hello-app-py-ctr
        image: bzumby/hello_app_py:v1.3
        ports:
        - containerPort: 5000