apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-app-py-dpl
  labels:
    app: hello-app-py
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-app-py
  template:
    metadata:
      name: hello-app-py
      labels:
        app: hello-app-py

    spec:
      containers:
      - name: hello-app-py-ctr
        image: bzumby/hello_app_py
        ports:
        - containerPort: 5000
---
kind: Service
apiVersion: v1
metadata:
  name: hello-app-py-srv
  labels:
    app: hello-app-py
spec:
  selector:
    app: hello-app-py
  type: NodePort
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000